# TODO (Dev 1):
#
# class Contact(SQLModel, table=True): ...
# class Phone(SQLModel, table=True): ...

# TODO (Dev 2):
#
# class NoteTagLink(SQLModel, table=True): ...
# class Tag(SQLModel, table=True): ...
# class Note(SQLModel, table=True): ...
